version: "2"

run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects unused assignments
    - staticcheck   # Static analysis checks (includes gosimple)
    - unused        # Find unused code
    - misspell      # Find misspellings

  settings:
    errcheck:
      check-type-assertions: true

formatters:
  enable:
    - gofmt         # Check formatting
    - goimports     # Check imports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
